### ISSUE TITLE
`topic.produce` seems to require a schema

### ISSUE THREAD

**Issue by sdball** [jjlangholtz/kafka_rest#1]
Hello! I'm really liking the look of this wrapper around Confluent's kafka rest API!

I'm running into what looks like a bug with `topic.produce`:

```
> topic.produce("test")
NoMethodError: undefined method `serialized' for nil:NilClass
```

Getting into the trace:

```
kafka_rest/topic.rb:44:in `produce': undefined method `serialized' for nil:NilClass (NoMethodError)
```

Looking at the code:

```
if schema && schema.id
  payload[:value_schema_id] = schema.id
else
  payload[:value_schema] = schema.serialized # line 44
end
```

I'm guessing the logic is meant to fall through there and be something like:

```
if schema
  if schema.id
    payload[:value_schema_id] = schema.id
  else
    payload[:value_schema] = schema.serialized
  end
end
```

**Comment by jjlangholtz** [comment]
Thanks for reporting! Implemented the fix and released. I haven't touched this project in a little while but if you encounter any other issues I would be happy to try and fix.
